mindmap
  (Hardskills)
  ::icon(fa fa-laptop)
    (Electronics)
    ::icon(fa fa-microchip)
        Circuit/PCB designing
            Altium
            Eagle
            KiCad
        Prototyping
            Board assembly
            Test board creation
            Pretotyping
        Soldering
            Lead solder
            Lead free
            Heat gun
            SMD components
            Paste solder
    (IoT)
    ::icon(fa fa-cloud)
        Devices
            Raspberry Pi
            Pi Cam
            ESPCAM
            ESP32
            STM32
            Jetson NVIDIA
        Networking
            LoRa
            Zigbee
            BLE
            Mesh IoT Networks
            NB IoT
        Messaging
            MQTT
            RabbitMQ
            Kafka
            NATS
        Operating Systems
            FreeRTOS
            Zephyr
            BalenaOS
        Cloud
            BalenaCloud
    (DevOps)
    ::icon(fa fa-infinity)
        General tools
            Linux
            Shell
        Web
            Networking
            Web Protocols
            HTTP, SSL/TLS, SSH
        Containers & Orchestration
            Docker
            Kubernetes
        Cloud Providers
            AWS
            Azure
            Google Cloud Platform
        CI/CD
            Jenkins
            GitLab CI
            GitHub Actions
            Travis CI
            AWS Codepipeline
            Azure DevOps
        Monitoring
            Zabbix
    (Programming)
    ::icon(fa fa-book)
        Languages
            C/C++
            Rust
            Go
        Others
            Clean code
            Design patterns
    