mindmap
    (Soft skills)
    ::icon(fa fa-users)
        (Negócio/Produto)
        ::icon(fa fa-suitcase)
            Visão sistêmica de negócio/produto
            Conceber a visão de produtos físicos e digitais
            Definir e gerenciar o orçamento de produtos
            Definição de métricas de produto
            Formulação de estratégias, precificação e ações de marketing de produtos
        (Pessoal)
        ::icon(fa fa-user)
            Resolução de problemas
            Flexibilidade e capacidade de adaptação
            Comunicação
            Fortes habilidades de organização
            Qualidade em entregas
        (Projeto)
        ::icon(fa fa-search)
            Definir o backlog
            Identificar features
            Estabelecer o roadmap de produtos
        (Planejamento)
        ::icon(fa fa-edit)
            Participar da etapa de product discovery
            Identificação de hipóteses e da execução dos experimentos e produtos
            Realizar a modelagem de negócios de produtos e definir o Product Market Fit
        (Acompanhamento)
        ::icon(fa fa-sticky-note)
            Construção de experimentos e produtos
            Implementação dos roadmaps de produtos
            Resultados de métricas de produtos
